name: bioinfo
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - biopython
  - scikit-bio
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - pip
  - py3Dmol
  - pip:
    - vcfpy
  - samtools

