name: bioinfo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - biopython
  - scikit-bio
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - pip
  - pip:
    - vcfpy
  - r-base=4.2
  - r-irkernel
